parameters: {}
environment: {}
packages:
    - name: markdown-processor
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: markdownize
          binary: false
          main: ""
          runtime: nodejs:default
          web: true
          webSecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
    - name: backend-handler
      environment: {
          DATABASE_URL: ${DATABASE_URL}
      }
      parameters: {}
      annotations: {}
      functions:
        - name: login
          binary: false
          main: ""
          runtime: nodejs:default
          web: true
          webSecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
        - name: register
          binary: false
          main: ""
          runtime: nodejs:default
          web: true
          webSecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}


